global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'my_exporter_job'
    static_configs:
      - targets: ['host.docker.internal:9095']
    metrics_path: /metrics
    scheme: http
    bearer_token: testToken
